### ISSUE TITLE
Getting error loading settings

### ISSUE THREAD

**Issue by kiwiluver75** [jamon/playmusic#24]
Am I the only one getting this message?

error [Error: Login Failed, unable to load settings:Error: error loading settings: Error: 404 error from server]

**Comment by jamon** [comment]
It's definitely widespread.  I'm digging into it--I think it's authentication related, but it's hard to pinpoint what part is the issue, because the authentication is successful, but the request for settings gives a 404.  I'm going to probably have to reverse engineer one of the other libraries to figure out what's going on differently.

**Comment by kiwiluver75** [comment]
I think i've figured it out. Trying out the changes locally. The only problem is i'm not too experienced in git, so I will try to explain the changes here.

**Comment by kiwiluver75** [comment]
IT WORKS!! I'll try my best to send a pull request

**Comment by jamon** [comment]
awesome.  however you can get the code to me, I'll work through it =)

**Comment by kiwiluver75** [comment]
Sent pull request.

**Comment by jamon** [comment]
merged, will release shortly
